"""synapse incident hub users sessions.

Revision ID: f09759fd53e8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-04 10:57:55.874702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from opsmemory.db.types import GUID

revision: str = "f09759fd53e8"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("auth_provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "incident_links",
        sa.Column("source_id", GUID(length=36), nullable=False),
        sa.Column("target_id", GUID(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "shared_services",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["incidents.id"],
            name=op.f("fk_incident_links_source_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["incidents.id"],
            name=op.f("fk_incident_links_target_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_links")),
    )
    op.create_index(
        op.f("ix_incident_links_source_id"), "incident_links", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_links_target_id"), "incident_links", ["target_id"], unique=False
    )
    op.add_column("documents", sa.Column("incident_id", GUID(length=36), nullable=True))
    op.create_index(op.f("ix_documents_incident_id"), "documents", ["incident_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_documents_incident_id_incidents"),
        "documents",
        "incidents",
        ["incident_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("incidents", sa.Column("number", sa.Integer(), nullable=True))
    op.add_column(
        "incidents",
        sa.Column("archived", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "documentation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "incidents", sa.Column("documentation_generated_at", sa.DateTime(), nullable=True)
    )
    op.create_index(op.f("ix_incidents_archived"), "incidents", ["archived"], unique=False)
    op.create_index(op.f("ix_incidents_number"), "incidents", ["number"], unique=True)
    op.drop_constraint(op.f("uq_meeting_summaries_meeting_id"), "meeting_summaries", type_="unique")
    op.drop_constraint(
        op.f("uq_meeting_transcripts_meeting_id"), "meeting_transcripts", type_="unique"
    )
    op.add_column("meetings", sa.Column("incident_id", GUID(length=36), nullable=True))
    op.drop_constraint(op.f("uq_meetings_recall_bot_id"), "meetings", type_="unique")
    op.create_index(op.f("ix_meetings_incident_id"), "meetings", ["incident_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_meetings_incident_id_incidents"),
        "meetings",
        "incidents",
        ["incident_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("memories", sa.Column("incident_id", GUID(length=36), nullable=True))
    op.create_index(op.f("ix_memories_incident_id"), "memories", ["incident_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_memories_incident_id_incidents"),
        "memories",
        "incidents",
        ["incident_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_memories_incident_id_incidents"), "memories", type_="foreignkey")
    op.drop_index(op.f("ix_memories_incident_id"), table_name="memories")
    op.drop_column("memories", "incident_id")
    op.drop_constraint(op.f("fk_meetings_incident_id_incidents"), "meetings", type_="foreignkey")
    op.drop_index(op.f("ix_meetings_incident_id"), table_name="meetings")
    op.create_unique_constraint(
        op.f("uq_meetings_recall_bot_id"),
        "meetings",
        ["recall_bot_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("meetings", "incident_id")
    op.create_unique_constraint(
        op.f("uq_meeting_transcripts_meeting_id"),
        "meeting_transcripts",
        ["meeting_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_meeting_summaries_meeting_id"),
        "meeting_summaries",
        ["meeting_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_incidents_number"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_archived"), table_name="incidents")
    op.drop_column("incidents", "documentation_generated_at")
    op.drop_column("incidents", "documentation")
    op.drop_column("incidents", "archived")
    op.drop_column("incidents", "number")
    op.drop_constraint(op.f("fk_documents_incident_id_incidents"), "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_incident_id"), table_name="documents")
    op.drop_column("documents", "incident_id")
    op.drop_index(op.f("ix_incident_links_target_id"), table_name="incident_links")
    op.drop_index(op.f("ix_incident_links_source_id"), table_name="incident_links")
    op.drop_table("incident_links")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
