"""Schemas for meeting endpoints."""

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from opsmemory.domain.enums import MeetingProvider, MeetingStatus


class MeetingCreate(BaseModel):
    """Invite the OpsMemory bot into a meeting.

    ``incident_id`` set → the meeting enriches that incident. Omitted → a new
    incident is auto-created from the transcript (title generated by AI).
    """

    meeting_url: str = Field(min_length=8, max_length=2000)
    title: str | None = Field(default=None, max_length=500)
    provider: MeetingProvider | None = Field(
        default=None, description="Inferred from the URL when omitted."
    )
    organizer: str | None = Field(default=None, max_length=200)
    incident_id: uuid.UUID | None = Field(
        default=None, description="Existing incident to enrich; omit for a new incident."
    )


class MeetingInvite(BaseModel):
    """Invite the bot for a specific incident (incident id comes from the path)."""

    meeting_url: str = Field(min_length=8, max_length=2000)
    title: str | None = Field(default=None, max_length=500)
    organizer: str | None = Field(default=None, max_length=200)


class MeetingOut(BaseModel):
    """A recorded meeting and its processing state."""

    id: uuid.UUID
    recall_bot_id: str
    meeting_url: str
    provider: MeetingProvider
    title: str | None
    organizer: str | None
    status: MeetingStatus
    incident_id: uuid.UUID | None
    recording_url: str | None
    transcript_url: str | None
    transcript_downloaded: bool
    summary_generated: bool
    cognee_synced: bool
    error: str | None
    duration_seconds: int | None
    participants: list[Any]
    started_at: datetime | None
    ended_at: datetime | None
    created_at: datetime

    model_config = {"from_attributes": True}


class MeetingDetailOut(MeetingOut):
    """Meeting including its extracted summary (when generated)."""

    summary: str | None = None
    structured: dict[str, Any] | None = None


class WebhookAck(BaseModel):
    """Immediate webhook acknowledgment."""

    ok: bool
    handled: bool
